-- ==============================================================================
-- GangnamOn Database Schema (Final Version for Launch)
-- ==============================================================================
-- 1. Enable necessary extensions
create extension if not exists "uuid-ossp";
-- 2. PROFILES Table (Extends Supabase Auth)
create table public.profiles (
     id uuid references auth.users not null primary key,
     username text unique not null,
     full_name text,
     avatar_url text,
     -- GangnamOn Specifics
     beans int default 1250,
     -- 'Credit' (Kong)
     location text default '강남 역삼',
     bio text,
     -- Social Traits
     gender text check (gender in ('male', 'female', 'other')),
     birth_year int,
     mbti text,
     interests text [],
     -- e.g. ['#Exercise', '#Coffee']
     -- Trust Score
     manner_temp float default 36.5,
     -- Stats
     visitors_today int default 0,
     visitors_total int default 0,
     updated_at timestamp with time zone,
     created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 3. POSTS (Feeds, Market, Dining, Owner's Note)
create table public.posts (
     id bigint generated by default as identity primary key,
     author_id uuid references public.profiles(id) not null,
     type text not null,
     -- 'market', 'gathering', 'owners_note'
     title text not null,
     content text,
     -- Market Specifics
     price int default 0,
     is_sold boolean default false,
     -- Dining/Gathering Specifics
     max_participants int,
     current_participants int default 1,
     -- Location (Core for Map)
     location_name text,
     -- e.g. "Unjeong Lake Park"
     latitude double precision,
     longitude double precision,
     image_urls text [],
     -- Denormalized Counts
     likes_count int default 0,
     comment_count int default 0,
     created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 4. INTERACTIONS (Likes, Bookmarks)
create table public.post_likes (
     user_id uuid references public.profiles(id) not null,
     post_id bigint references public.posts(id) not null,
     created_at timestamp with time zone default timezone('utc'::text, now()),
     primary key (user_id, post_id)
);
-- 5. NOTIFICATIONS (For Push Alerts)
create table public.notifications (
     id bigint generated by default as identity primary key,
     user_id uuid references public.profiles(id) not null,
     -- Recipient
     title text not null,
     message text not null,
     is_read boolean default false,
     type text,
     -- 'event', 'chat', 'notice'
     created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 6. CHAT SYSTEM
create table public.chat_rooms (
     id uuid default uuid_generate_v4() primary key,
     created_at timestamp with time zone default timezone('utc'::text, now())
);
create table public.chat_participants (
     room_id uuid references public.chat_rooms(id) not null,
     user_id uuid references public.profiles(id) not null,
     primary key (room_id, user_id)
);
create table public.chat_messages (
     id bigint generated by default as identity primary key,
     room_id uuid references public.chat_rooms(id) not null,
     sender_id uuid references public.profiles(id) not null,
     content text not null,
     is_read boolean default false,
     created_at timestamp with time zone default timezone('utc'::text, now())
);
-- ==============================================================================
-- 7. TRIGGERS & FUNCTIONS (CRITICAL)
-- ==============================================================================
-- A. Auto-create Profile on Signup
create or replace function public.handle_new_user() returns trigger as $$ begin
insert into public.profiles (id, username, full_name, avatar_url, beans)
values (
          new.id,
          new.raw_user_meta_data->>'username',
          new.raw_user_meta_data->>'full_name',
          coalesce(new.raw_user_meta_data->>'avatar_url', ''),
          1000 -- Welcome Bonus
     );
return new;
end;
$$ language plpgsql security definer;
-- Trigger definition
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after
insert on auth.users for each row execute procedure public.handle_new_user();
-- ==============================================================================
-- 8. ROW LEVEL SECURITY (RLS)
-- ==============================================================================
alter table profiles enable row level security;
alter table posts enable row level security;
alter table post_likes enable row level security;
alter table notifications enable row level security;
-- Simple Policies (Open for Demo)
create policy "Public Read Profiles" on profiles for
select using (true);
create policy "User Update Own Profile" on profiles for
update using (auth.uid() = id);
create policy "Public Read Posts" on posts for
select using (true);
create policy "Auth Create Posts" on posts for
insert with check (auth.role() = 'authenticated');
create policy "Auth Update Own Posts" on posts for
update using (auth.uid() = author_id);
create policy "User Read Own Notis" on notifications for
select using (auth.uid() = user_id);