-- ==============================================================================
-- PajuOn Database RESET & INSTALL Script
-- WARNING: This will DELETE existing data in 'profiles', 'posts', etc.
-- Use this to get a fresh start for your Launch.
-- ==============================================================================
-- 1. DROP Existing Tables (Clean Slate)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.chat_messages;
DROP TABLE IF EXISTS public.chat_participants;
DROP TABLE IF EXISTS public.chat_rooms;
DROP TABLE IF EXISTS public.notifications;
DROP TABLE IF EXISTS public.post_likes;
DROP TABLE IF EXISTS public.posts;
DROP TABLE IF EXISTS public.romance_interactions;
DROP TABLE IF EXISTS public.school_alumni;
DROP TABLE IF EXISTS public.schools;
DROP TABLE IF EXISTS public.profiles CASCADE;
-- ==============================================================================
-- 2. CREATE Tables (Fresh)
-- ==============================================================================
create extension if not exists "uuid-ossp";
-- PROFILES
create table public.profiles (
     id uuid references auth.users not null primary key,
     username text unique,
     full_name text,
     avatar_url text,
     beans int default 1250,
     location text default '파주 운정',
     bio text,
     gender text check (gender in ('male', 'female', 'other')),
     birth_year int,
     mbti text,
     interests text [],
     manner_temp float default 36.5,
     visitors_today int default 0,
     visitors_total int default 0,
     updated_at timestamp with time zone,
     created_at timestamp with time zone default timezone('utc'::text, now())
);
-- POSTS
create table public.posts (
     id bigint generated by default as identity primary key,
     author_id uuid references public.profiles(id) not null,
     type text not null,
     title text not null,
     content text,
     price int default 0,
     is_sold boolean default false,
     max_participants int,
     current_participants int default 1,
     location_name text,
     latitude double precision,
     longitude double precision,
     image_urls text [],
     likes_count int default 0,
     comment_count int default 0,
     created_at timestamp with time zone default timezone('utc'::text, now())
);
-- LIKES
create table public.post_likes (
     user_id uuid references public.profiles(id) not null,
     post_id bigint references public.posts(id) not null,
     created_at timestamp with time zone default timezone('utc'::text, now()),
     primary key (user_id, post_id)
);
-- NOTIFICATIONS
create table public.notifications (
     id bigint generated by default as identity primary key,
     user_id uuid references public.profiles(id) not null,
     title text not null,
     message text not null,
     is_read boolean default false,
     type text,
     created_at timestamp with time zone default timezone('utc'::text, now())
);
-- CHAT
create table public.chat_rooms (
     id uuid default uuid_generate_v4() primary key,
     created_at timestamp with time zone default timezone('utc'::text, now())
);
create table public.chat_participants (
     room_id uuid references public.chat_rooms(id) not null,
     user_id uuid references public.profiles(id) not null,
     primary key (room_id, user_id)
);
create table public.chat_messages (
     id bigint generated by default as identity primary key,
     room_id uuid references public.chat_rooms(id) not null,
     sender_id uuid references public.profiles(id) not null,
     content text not null,
     is_read boolean default false,
     created_at timestamp with time zone default timezone('utc'::text, now())
);
-- ==============================================================================
-- 3. TRIGGERS & RLS
-- ==============================================================================
create or replace function public.handle_new_user() returns trigger as $$ begin
insert into public.profiles (id, username, full_name, avatar_url, beans)
values (
          new.id,
          new.raw_user_meta_data->>'username',
          new.raw_user_meta_data->>'full_name',
          coalesce(new.raw_user_meta_data->>'avatar_url', ''),
          1000
     );
return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
after
insert on auth.users for each row execute procedure public.handle_new_user();
alter table profiles enable row level security;
alter table posts enable row level security;
alter table post_likes enable row level security;
alter table notifications enable row level security;
create policy "Public Read Profiles" on profiles for
select using (true);
create policy "User Update Own Profile" on profiles for
update using (auth.uid() = id);
create policy "Public Read Posts" on posts for
select using (true);
create policy "Auth Create Posts" on posts for
insert with check (auth.role() = 'authenticated');
create policy "Auth Update Own Posts" on posts for
update using (auth.uid() = author_id);
create policy "User Read Own Notis" on notifications for
select using (auth.uid() = user_id);