-- ==============================================================================
-- PajuOn Database Schema (Supabase / PostgreSQL)
-- ==============================================================================
-- 1. PROFILES Table (Extends Supabase Auth)
-- Stores extensive user information including credits (beans) and mini-homepage data.
create table public.profiles (
  id uuid references auth.users not null primary key,
  -- Links to Supabase Auth User ID
  username text unique not null,
  full_name text,
  avatar_url text,
  -- High-res profile image
  unlocked_styles text [] default '{"lorelei", "avataaars"}',
  -- Array of unlocked avatar styles
  gallery_urls text [] default '{}',
  -- Array of image URLs for Mini-homepage gallery
  -- PajuOn Specifics
  beans int default 1250,
  -- 'Credit' (Kong)
  location text default '파주 운정',
  -- Residence
  bio text,
  -- Simple bio
  status_message text,
  -- Mini-homepage status message
  -- Romance & Social specific
  gender text,
  -- 'male', 'female', etc.
  birth_year int,
  -- For age calculation
  mbti text,
  -- e.g. 'ENFP'
  job text,
  interests text [],
  -- Tags like ['#Exercise', '#Coffee']
  -- Stats
  visitors_today int default 0,
  visitors_total int default 0,
  updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 1.1 ROMANCE INTERACTIONS
-- Tracks likes, passes, and matches
create table public.romance_interactions (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) not null,
  target_id uuid references public.profiles(id) not null,
  action_type text not null,
  -- 'like', 'superlike', 'pass'
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(actor_id, target_id) -- Prevent duplicate actions
);
-- 2. SCHOOLS & ALUMNI Structure
-- Allows finding friends by school and graduation year.
create table public.schools (
  id bigint generated by default as identity primary key,
  name text not null,
  -- e.g., "문산고등학교"
  region text default '파주',
  category text -- e.g., "High", "Middle", "Elementary"
);
create table public.school_alumni (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  school_id bigint references public.schools(id) not null,
  grad_year int not null,
  -- e.g., 2008
  unique(user_id, school_id) -- Prevent duplicate entries for same school
);
-- 3. COMMUNITY & MARKET Table
-- Handles all feed items including Used Market and Gatherings.
create table public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) not null,
  type text not null,
  -- 'market', 'gathering', 'club', 'romance_profile'
  title text not null,
  content text,
  -- Market Specifics
  price int default 0,
  is_sold boolean default false,
  -- Gathering Specifics
  max_participants int,
  current_participants int default 1,
  -- Common
  location text,
  -- Specific location for the trade/meetup
  image_urls text [],
  -- Multiple images
  likes_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 4. GUESTBOOK (Mini-homepage)
-- Visitors leaving messages on a user's profile.
create table public.guestbook_entries (
  id bigint generated by default as identity primary key,
  host_id uuid references public.profiles(id) not null,
  -- Whose homepage is it?
  author_id uuid references public.profiles(id) not null,
  -- Who wrote it?
  content text not null,
  is_secret boolean default false,
  -- "Secret" message feature
  created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 5. CHAT SYSTEM
-- 1:1 Chat logs.
create table public.chat_rooms (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
-- Junction table for chat participants
create table public.chat_participants (
  room_id uuid references public.chat_rooms(id) not null,
  user_id uuid references public.profiles(id) not null,
  primary key (room_id, user_id)
);
create table public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id uuid references public.chat_rooms(id) not null,
  sender_id uuid references public.profiles(id) not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
-- ==============================================================================
-- Row Level Security (RLS) Policies (Examples)
-- ==============================================================================
-- Enable RLS on tables
alter table profiles enable row level security;
alter table posts enable row level security;
-- Profiles are viewable by everyone
create policy "Public profiles are viewable by everyone" on profiles for
select using (true);
-- Users can insert their own profile
create policy "Users can insert their own profile" on profiles for
insert with check (auth.uid() = id);
-- Users can update own profile
create policy "Users can update own profile" on profiles for
update using (auth.uid() = id);
-- ==============================================================================
-- 6. RPC Functions (Server-side Logic)
-- ==============================================================================
-- Purchase Avatar Style Function
-- Securely deducts beans and unlocks a style in a single transaction.
create or replace function public.purchase_avatar_style(
    style_id text,
    price int,
    user_id uuid default auth.uid()
  ) returns boolean language plpgsql security definer -- Runs with privileges of the function creator (admin)
  as $$
declare current_beans int;
current_styles text [];
begin -- 1. Check current balance
select beans,
  unlocked_styles into current_beans,
  current_styles
from public.profiles
where id = user_id;
if current_beans is null then raise exception 'User not found';
end if;
if current_beans < price then return false;
-- Not enough beans
end if;
if style_id = any(current_styles) then return true;
-- Already unlocked
end if;
-- 2. Deduct beans and add style
update public.profiles
set beans = beans - price,
  unlocked_styles = array_append(current_styles, style_id)
where id = user_id;
return true;
end;
$$;